### ISSUE TITLE
错误：AttributeError: 'ThreadedDict' object has no attribute 'app_stack'

### ISSUE THREAD

**Issue by sbcqw93** [qiyeboy/IPProxyPool#103]
程序运行一段时间，出现错误：
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/python-3.6.0/lib/python3.6/site-packages/web.py-0.40.dev0-py3.6.egg/web/wsgiserver/wsgiserver3.py", line 1089, in communicate
    req.respond()
  File "/usr/python-3.6.0/lib/python3.6/site-packages/web.py-0.40.dev0-py3.6.egg/web/wsgiserver/wsgiserver3.py", line 877, in respond
    self.server.gateway(self).respond()
  File "/usr/python-3.6.0/lib/python3.6/site-packages/web.py-0.40.dev0-py3.6.egg/web/wsgiserver/wsgiserver3.py", line 1980, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/python-3.6.0/lib/python3.6/site-packages/web.py-0.40.dev0-py3.6.egg/web/httpserver.py", line 324, in __call__
    return self.app(environ, xstart_response)
  File "/usr/python-3.6.0/lib/python3.6/site-packages/web.py-0.40.dev0-py3.6.egg/web/httpserver.py", line 294, in __call__
    return self.app(environ, start_response)
  File "/usr/python-3.6.0/lib/python3.6/site-packages/web.py-0.40.dev0-py3.6.egg/web/application.py", line 295, in wsgi
    result = self.handle_with_processors()
  File "/usr/python-3.6.0/lib/python3.6/site-packages/web.py-0.40.dev0-py3.6.egg/web/application.py", line 267, in handle_with_processors
    return process(self.processors)
  File "/usr/python-3.6.0/lib/python3.6/site-packages/web.py-0.40.dev0-py3.6.egg/web/application.py", line 264, in process
    raise self.internalerror()
  File "/usr/python-3.6.0/lib/python3.6/site-packages/web.py-0.40.dev0-py3.6.egg/web/application.py", line 541, in internalerror
    parent = self.get_parent_app()
  File "/usr/python-3.6.0/lib/python3.6/site-packages/web.py-0.40.dev0-py3.6.egg/web/application.py", line 526, in get_parent_app
    if self in web.ctx.app_stack:
AttributeError: 'ThreadedDict' object has no attribute 'app_stack'

===============================================

出现此后，服务能正常访问，但一直出现这个错误，日志文件量，巨增。
软件环境：
python3.6.0
web.py (0.40.dev0)

**Comment by qiyeboy** [comment]
你是直接从github上clone的吗？你可以先试试release版本
