### ISSUE TITLE
使用mysql+pymysql，“from db.SqlHelper import SqlHelper as SqlHelper”，导入报错。

### ISSUE THREAD

**Issue by lovebaicai** [qiyeboy/IPProxyPool#114]
config配置：
```
DB_CONFIG = {
     'DB_CONNECT_TYPE': 'sqlalchemy',
     'DB_CONNECT_STRING' : 'mysql+pymysql://root:ubuntu@localhost/proxy?charset=utf8' #密码已改
```
报错：
```
Traceback (most recent call last):
  File "IPProxy.py", line 4, in <module>
     from api.apiServer import start_api_server
  File "/home/root/Workspace/IPProxyPool/api/apiServer.py", line 9, in <module>
    from db.DataStore import sqlhelper
  File "/home/root/Workspace/IPProxyPool/db/DataStore.py", line 17, in <module>
   raise Con_DB_Fail
util.exception.Con_DB_Fail: <exception str() failed>
```
使用mongo，redis都是ok的。请有时间帮忙看看，谢谢您！

**Comment by lovebaicai** [comment]
解决了。
需要在mysql建立一个```proxy```的database。
