### ISSUE TITLE
Mac版存在的问题。

### ISSUE THREAD

**Issue by zuoerboy** [qiyeboy/IPProxyPool#128]
python3.6
相关库：requests (2.18.3)、chardet (3.0.4)、web.py (0.40.dev0)、gevent (1.2.2)、psutil (5.4.1)、SQLAlchemy (1.1.15)

然后运行IPProxy.py后出现如下错误：
`Traceback (most recent call last):
  File "IPProxy.py", line 7, in <module>
     from validator.Validator import validator, getMyIP
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 154, in __exit__
  File "<frozen importlib._bootstrap>", line 106, in release
RuntimeError: cannot release un-acquired lock`

**Comment by cbc356326350** [comment]
+1

**Comment by lujqme** [comment]
+1

**Comment by mynameisshiy** [comment]
建议使用python2.7，反正我没碰到这些问题，反而是我使用pipenv后，web.py无法安装。后来我就直接换成flask了。目前完美运行中。
