### ISSUE TITLE
wrong not can import

### ISSUE THREAD

**Issue by 1225358814** [qiyeboy/IPProxyPool#133]
PS D:\workerspace\git\python\PhantomJS_and_selenium\IPProxyPool> python .\IPProxy.py
Traceback (most recent call last):
  File "D:\workerspace\git\python\PhantomJS_and_selenium\IPProxyPool\db\DataStore.py", line 13, in <module>
    from db.SqlHelper import SqlHelper as SqlHelper
  File "D:\workerspace\git\python\PhantomJS_and_selenium\IPProxyPool\db\SqlHelper.py", line 3, in <module>
    from sqlalchemy import Column, Integer, String, DateTime, Numeric, create_engine, VARCHAR
ImportError: No module named 'sqlalchemy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\IPProxy.py", line 4, in <module>
    from api.apiServer import start_api_server
  File "D:\workerspace\git\python\PhantomJS_and_selenium\IPProxyPool\api\apiServer.py", line 9, in <module>
    from db.DataStore import sqlhelper
  File "D:\workerspace\git\python\PhantomJS_and_selenium\IPProxyPool\db\DataStore.py", line 17, in <module>
    raise Con_DB_Fail
util.exception.Con_DB_Fail: <exception str() failed>

**Comment by 1225358814** [comment]
已经好了  pip3 install bitarray
如果这个无法安装 就去升级一下pip版本  python -m pip install --upgrade pip
或是升级在pycharm里升级 setuptool
