### ISSUE TITLE
python3 问题有点多啊

### ISSUE THREAD

**Issue by 7733012** [qiyeboy/IPProxyPool#150]
Traceback (most recent call last):
  File "C:/python3.6.3/Lib/site-packages/sqlalchemy/engine/base.py", line 15, in <module>
    from .. import exc, util, log, interfaces
ValueError: attempted relative import beyond top-level package

**Comment by gitscamI** [comment]
不是一般的多，稀烂

**Comment by JoffreyN** [comment]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ZP\AppData\Local\Temp\pip-install-r7jpx727\web.py\setup.py", line 6, in <module>
        from web import __version__
      File "C:\Users\ZP\AppData\Local\Temp\pip-install-r7jpx727\web.py\web\__init__.py", line 14, in <module>
        import utils, db, net, wsgi, http, webapi, httpserver, debugerror
    ModuleNotFoundError: No module named 'net'
    
    E:\Users\ZP\Desktop\5-2\py\IPProxyPool>pip install net
    Collecting net
      Could not find a version that satisfies the requirement net (from versions: )
    No matching distribution found for net
-----------------------------------------------------------------------------------------------------------------

**Comment by huht123** [comment]
用3被坑死 果断放弃3
