### ISSUE TITLE
运行项目的时候报错,提示：from validator.Validator import validator, getMyIP

### ISSUE THREAD

**Issue by landonzeng** [qiyeboy/IPProxyPool#162]
Traceback (most recent call last):
  File "c:/Users/landon/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:/Users/landon/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles\lib\python\ptvsd\__main__.py", line 434, in main
    run()
  File "c:/Users/landon/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles\lib\python\ptvsd\__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\landon\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\landon\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\landon\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "f:\MyWorkFile\Coding文件\PythonSpider\IPProxyPool-master\IPProxy.py", line 7, in <module>
    from validator.Validator import validator, getMyIP
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 152, in __exit__
  File "<frozen importlib._bootstrap>", line 107, in release
RuntimeError: cannot release un-acquired lock
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "src\gevent\_abstract_linkable.py", line 169, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src\gevent\_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
Exception in thread ptvsd.stopping:
Traceback (most recent call last):
  File "C:\Users\landon\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\landon\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\threading.py", line 177, in run
    super(Thread, self).run()
  File "C:\Users\landon\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:/Users/landon/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles\lib\python\ptvsd\wrapper.py", line 867, in stop
    wait()
  File "c:/Users/landon/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles\lib\python\ptvsd\daemon.py", line 453, in wait_debugger
    lock_wait(lock, timeout)
  File "c:/Users/landon/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles\lib\python\ptvsd\_util.py", line 104, in lock_wait
    if not _lock_acquire(lock, timeout):
  File "c:/Users/landon/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles\lib\python\ptvsd\_util.py", line 113, in _lock_acquire
    return lock.acquire(timeout=timeout)
  File "C:\Users\landon\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\thread.py", line 84, in acquire
    return BoundedSemaphore.acquire(self, blocking, timeout)
  File "src\gevent\_semaphore.py", line 100, in gevent.__semaphore.Semaphore.acquire
  File "src\gevent\_semaphore.py", line 128, in gevent.__semaphore.Semaphore.acquire
  File "src\gevent\_abstract_linkable.py", line 192, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src\gevent\_abstract_linkable.py", line 165, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src\gevent\_abstract_linkable.py", line 169, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src\gevent\_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
gevent.exceptions.LoopExit: This operation would block forever
        Hub: <Hub '' at 0x1a9f1937778 default pending=0 ref=0 thread_ident=0x8310>
        Handles:
[HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001A9EEF38E28>, type=b'check', watcher=<loop at 0x1a9f01d0e48 default pending=0 ref=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001A9ECFF2698>, type=b'timer', watcher=<loop at 0x1a9f01d0e48 default pending=0 ref=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001A9EEF39668>, type=b'prepare', watcher=<loop at 0x1a9f01d0e48 default pending=0 ref=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001A9EEF395B8>, type=b'check', watcher=<loop at 0x1a9f01d0e48 default pending=0 ref=0>, ref=1, active=0, closing=0)]

  File "src\gevent\_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switchWithLoop.switch                                                                                        h
  File "src\gevent\__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
gevent.exceptions.LoopExit: This operation would block forever
        Hub: <Hub '' at 0x1a9f187d270 default default pending=0 ref=0 thread_ident=0x4358>             0x1a9f1721470 default default pending=0 ref=0>, ref=0, active=1, closing=0),
        Handles:                                                                                       0x1a9f1721470 default default pending=0 ref=0>, ref=0, active=1, closing=0),
[HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001A9EEF38B68>, type=b'check', watcher=<loop at t 0x1a9f1721470 default default pending=0 ref=0>, ref=0, active=1, closing=0),
0x1a9f1721470 default default pending=0 ref=0>, ref=0, active=1, closing=0),                           0x1a9f1721470 default default pending=0 ref=0>, ref=1, active=0, closing=0)]
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001A9ECFF2EB8>, type=b'timer', watcher=<loop at
0x1a9f1721470 default default pending=0 ref=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001A9EEF39458>, type=b'prepare', watcher=<loop at 0x1a9f1721470 default default pending=0 ref=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001A9EEF38CC8>, type=b'check', watcher=<loop at
0x1a9f1721470 default default pending=0 ref=0>, ref=1, active=0, closing=0)]

![1](https://user-images.githubusercontent.com/7336781/58854714-b2a52e00-86d0-11e9-995b-ad686610b4cc.png)
![2](https://user-images.githubusercontent.com/7336781/58854727-b933a580-86d0-11e9-9a41-a15e054f4f14.png)

**Comment by landonzeng** [comment]
@qiyeboy 能帮忙看看么谢谢
