### ISSUE TITLE
你好，我用你的这个代码时报如下错误，不知道哪错了，谢谢赐教

### ISSUE THREAD

**Issue by zhouming2gongmin** [qiyeboy/IPProxyPool#22]
Connected to pydev debugger (build 143.1559)
Exception AttributeError: "'NoneType' object has no attribute 'getpid'" in <Finalize object, dead> ignored
Error in sys.excepthook:
Traceback (most recent call last):
Error in sys.excepthook:
Traceback (most recent call last):
  File "D:\Program Files (x86)\JetBrains\PyCharm 5.0.3\helpers\pydev\pydevd_breakpoints.py", line 89, in _excepthook
  File "D:\Program Files (x86)\JetBrains\PyCharm 5.0.3\helpers\pydev\pydevd_breakpoints.py", line 89, in _excepthook
        _original_excepthook(exctype, value, tb)
_original_excepthook(exctype, value, tb)
TypeErrorTypeError: : 'NoneType' object is not callable'NoneType' object is not callable

Original exception was:
Traceback (most recent call last):

Original exception was:
Traceback (most recent call last):
  File "gevent\corecext.pyx", line 360, in gevent.corecext.loop.handle_error (gevent/gevent.corecext.c:6344)
  File "gevent\corecext.pyx", line 360, in gevent.corecext.loop.handle_error (gevent/gevent.corecext.c:6344)
  File "D:\Python27\lib\site-packages\gevent\hub.py", line 563, in handle_error
  File "D:\Python27\lib\site-packages\gevent\hub.py", line 563, in handle_error
        self.print_exception(context, type, value, tb)
self.print_exception(context, type, value, tb)
  File "D:\Python27\lib\site-packages\gevent\hub.py", line 588, in print_exception
  File "D:\Python27\lib\site-packages\gevent\hub.py", line 588, in print_exception
        errstream = sys.stderr
errstream = sys.stderr
AttributeErrorAttributeError: : 'NoneType' object has no attribute 'stderr''NoneType' object has no attribute 'stderr'

进程已结束,退出代码0

**Comment by qiyeboy** [comment]
首先不是代码的问题，应该是你pycharm的问题，你试一下直接使用python能否运行。

**Comment by Duanexiao** [comment]
@qiyeboy 请问存在数据库里面的IP会每天验证是否可用吗？

**Comment by qiyeboy** [comment]
默认一个小时检测一次，可以在config中配置

**Comment by qiyeboy** [comment]
@Duanexiao

**Comment by Duanexiao** [comment]
@qiyeboy 谢谢
