### ISSUE TITLE
python3 环境使用 pymongo 错误

### ISSUE THREAD

**Issue by crysehillmes** [qiyeboy/IPProxyPool#47]
OS: Windows 10 x64 1607
Python: 3.5.2

`config.py` 中使用 
```python
'DB_CONNECT_TYPE': 'pymongo',  
'DB_CONNECT_STRING': 'mongodb://localhost:27017/'
```
运行出现异常：
```
Traceback (most recent call last):
  File "IPProxy.py", line 7, in <module>
    from validator.Validator import validator, getMyIP
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 171, in __exit__
  File "<frozen importlib._bootstrap>", line 123, in release
RuntimeError: cannot release un-acquired lock
```
使用 `sqlalchemy` 没有问题。

另外有个建议，如果正在抓取代理时通过接口获取代理地址，控制台输出的抓取进度会被 HTTP 请求的 log 覆盖，希望能保留进度而不是覆盖。

**Comment by qiyeboy** [comment]
在家中，等过完年再维护

**Comment by NoraGithub** [comment]
@qiyeboy mac环境下也遇到该问题，请问如何解决？pymongo 3.4.0 python 3.5.0
