### ISSUE TITLE
Lost connection to MySQL server during query问题

### ISSUE THREAD

**Issue by pan7an** [qiyeboy/IPProxyPool#61]
使用sqlalchemy，pymysql。
后台启动进程，是不是会报数据库链接丢失问题
`Traceback (most recent call last): num :40,Fail ip num:0
  File "/root/.pyenv/versions/ipproxy-3.5.2/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/root/.pyenv/versions/ipproxy-3.5.2/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 469, in do_execute
    cursor.execute(statement, parameters)
  File "/root/.pyenv/versions/ipproxy-3.5.2/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/root/.pyenv/versions/ipproxy-3.5.2/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/root/.pyenv/versions/ipproxy-3.5.2/lib/python3.5/site-packages/pymysql/connections.py", line 852, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.pyenv/versions/ipproxy-3.5.2/lib/python3.5/site-packages/pymysql/connections.py", line 1053, in _read_query_result
    result.read()
  File "/root/.pyenv/versions/ipproxy-3.5.2/lib/python3.5/site-packages/pymysql/connections.py", line 1336, in read
    first_packet = self.connection._read_packet()
  File "/root/.pyenv/versions/ipproxy-3.5.2/lib/python3.5/site-packages/pymysql/connections.py", line 983, in _read_packet
    packet_header = self._read_bytes(4)
  File "/root/.pyenv/versions/ipproxy-3.5.2/lib/python3.5/site-packages/pymysql/connections.py", line 1029, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')`

**Comment by ResolveWang** [comment]
可能会报错，没用过web.py,但是使用flask的经验告诉我可以这么做：
`SQLALCHEMY_TRACK_MODIFICATIONS = False`
`SQLALCHEMY_POOL_RECYCLE = 1800`

你可以试试
