### ISSUE TITLE
启动程序后访问127.0.0.1:8000导致程序崩溃

### ISSUE THREAD

**Issue by ResolveWang** [qiyeboy/IPProxyPool#63]
```
IPProxyPool----->>>>>>>>beginning
http://0.0.0.0:8000/
IPProxyPool----->>>>>>>>db exists ip:33
IPProxyPool----->>>>>>>>now ip num < MINNUM,start crawling...
```
```
LoopExit('This operation would block forever', <Hub at 0x7f66f9bbfcc0 epoll pending=0 ref=0 fileno=16>)
Traceback (most recent call last):
  File "/home/wpm/venv/ipproxy/lib/python3.5/site-packages/web.py-0.40.dev0-py3.5.egg/web/wsgiserver/wsgiserver3.py", line 1079, in communicate
    req.parse_request()
  File "/home/wpm/venv/ipproxy/lib/python3.5/site-packages/web.py-0.40.dev0-py3.5.egg/web/wsgiserver/wsgiserver3.py", line 602, in parse_request
    success = self.read_request_line()
  File "/home/wpm/venv/ipproxy/lib/python3.5/site-packages/web.py-0.40.dev0-py3.5.egg/web/wsgiserver/wsgiserver3.py", line 635, in read_request_line
    request_line = self.rfile.readline()
  File "/home/wpm/venv/ipproxy/lib/python3.5/site-packages/web.py-0.40.dev0-py3.5.egg/web/wsgiserver/wsgiserver3.py", line 293, in readline
    data = self.rfile.readline(256)
  File "/usr/lib/python3.5/_pyio.py", line 510, in readline
    b = self.read(nreadahead())
  File "/usr/lib/python3.5/_pyio.py", line 494, in nreadahead
    readahead = self.peek(1)
  File "/usr/lib/python3.5/_pyio.py", line 1062, in peek
    return self._peek_unlocked(size)
  File "/usr/lib/python3.5/_pyio.py", line 1069, in _peek_unlocked
    current = self.raw.read(to_read)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/home/wpm/venv/ipproxy/lib/python3.5/site-packages/gevent/_socket3.py", line 385, in recv_into
    self._wait(self._read_event)
  File "/home/wpm/venv/ipproxy/lib/python3.5/site-packages/gevent/_socket3.py", line 157, in _wait
    self.hub.wait(watcher)
  File "/home/wpm/venv/ipproxy/lib/python3.5/site-packages/gevent/hub.py", line 651, in wait
    result = waiter.get()
  File "/home/wpm/venv/ipproxy/lib/python3.5/site-packages/gevent/hub.py", line 899, in get
    return self.hub.switch()
  File "/home/wpm/venv/ipproxy/lib/python3.5/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x7f66f9bbfcc0 epoll pending=0 ref=0 fileno=16>)
```

**Comment by xrlin** [comment]
@qiyeboy 我今天也遇到同样的问题, 在另一台电脑使用（window10 wsl环境）却没问题。

**Comment by orzmoe** [comment]
访问127.0.0.1:8000后显示这个，偶尔正常
`
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/web/wsgiserver/__init__.py", line 1235, in communicate
    req.parse_request()
  File "/usr/local/lib/python2.7/dist-packages/web/wsgiserver/__init__.py", line 531, in parse_request
    self.read_request_line()
  File "/usr/local/lib/python2.7/dist-packages/web/wsgiserver/__init__.py", line 559, in read_request_line
    request_line = self.rfile.readline()
  File "/usr/local/lib/python2.7/dist-packages/web/wsgiserver/__init__.py", line 231, in readline
    data = self.rfile.readline(256)
  File "/usr/local/lib/python2.7/dist-packages/web/wsgiserver/__init__.py", line 1057, in readline
    data = self.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/dist-packages/web/wsgiserver/__init__.py", line 933, in recv
    data = self._sock.recv(size)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_socket2.py", line 283, in recv
    self._wait(self._read_event)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_socket2.py", line 182, in _wait
    self.hub.wait(watcher)
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 651, in wait
    result = waiter.get()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 899, in get
    return self.hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
LoopExit: ('This operation would block forever', <Hub at 0x7fb372c4caf0 epoll pending=0 ref=0 fileno=17>)
`

**Comment by xrlin** [comment]
我也发现这是一个偶发情况，估计是可供调动的进程池不足。

**Comment by ResolveWang** [comment]
错误提示的是进程被阻塞了啊，怎么会是进程池的调度问题

**Comment by qiyeboy** [comment]
@ResolveWang @xrlin 你们是用的最新的吧。如果是的话，就先用一下releases v1.0,我把问题复现一下

**Comment by ResolveWang** [comment]
我直接clone的，没有用releases的版本

**Comment by qiyeboy** [comment]
@ResolveWang @xrlin 解决了，你们测试一下

**Comment by xrlin** [comment]
@qiyeboy 更新后没问题了

**Comment by ResolveWang** [comment]
现在没问题了
