### ISSUE TITLE
每刷新两次页面就有一次报错，详情如下

### ISSUE THREAD

**Issue by JNCoder** [qiyeboy/IPProxyPool#64]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/web/application.py", line 239, in process
    return self.handle()
  File "/Library/Python/2.7/site-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/Library/Python/2.7/site-packages/web/application.py", line 462, in _delegate
    return handle_class(cls)
  File "/Library/Python/2.7/site-packages/web/application.py", line 438, in handle_class
    return tocall(*args)
  File "/Users/cdsb/Codes/IPProxyPool/api/apiServer.py", line 27, in GET
    json_result = json.dumps(sqlhelper.select(inputs.get('count', None), inputs))
  File "/Users/cdsb/Codes/IPProxyPool/db/MongoHelper.py", line 60, in select
    result = (item['ip'], item['port'], item['score'])
  File "/Library/Python/2.7/site-packages/pymongo/cursor.py", line 1114, in next
    if len(self.__data) or self._refresh():
  File "/Library/Python/2.7/site-packages/pymongo/cursor.py", line 1036, in _refresh
    self.__collation))
  File "/Library/Python/2.7/site-packages/pymongo/cursor.py", line 873, in __send_message
    **kwargs)
  File "/Library/Python/2.7/site-packages/pymongo/mongo_client.py", line 905, in _send_message_with_response
    exhaust)
  File "/Library/Python/2.7/site-packages/pymongo/mongo_client.py", line 916, in _reset_on_error
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pymongo/server.py", line 136, in send_message_with_response
    response_data = sock_info.receive_message(1, request_id)
  File "/Library/Python/2.7/site-packages/pymongo/pool.py", line 452, in receive_message
    self._raise_connection_failure(error)
  File "/Library/Python/2.7/site-packages/pymongo/pool.py", line 552, in _raise_connection_failure
    raise error
LoopExit: ('This operation would block forever', <Hub at 0x10b661730 select pending=0 ref=0>)

**Comment by JNCoder** [comment]
mac环境下

**Comment by qiyeboy** [comment]
@JNCoder 解决了，你测试一下
