### ISSUE TITLE
SQL报错，抓取正常，但是访问页面读取就出现这个错误

### ISSUE THREAD

**Issue by lawmillion** [qiyeboy/IPProxyPool#67]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/web/application.py", line 239, in process
    return self.handle()
  File "/usr/local/lib/python2.7/site-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python2.7/site-packages/web/application.py", line 462, in _delegate
    return handle_class(cls)
  File "/usr/local/lib/python2.7/site-packages/web/application.py", line 438, in handle_class
    return tocall(*args)
  File "/usr/src/grab/api/apiServer.py", line 27, in GET
    json_result = json.dumps(sqlhelper.select(inputs.get('count', None), inputs))
  File "/usr/src/grab/db/SqlHelper.py", line 125, in select
    return query.order_by(Proxy.score.desc(), Proxy.speed).limit(count).all()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2679, in all
    return list(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2831, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2854, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1121, in _execute_context
    None, None)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1114, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 424, in _revalidate_connection
    "Can't reconnect until invalid "
StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'SELECT proxys.ip AS proxys_ip, proxys.port AS proxys_port, proxys.score AS proxys_score \nFROM proxys \nWHERE proxys.types = %(types_1)s ORDER BY proxys.score DESC, proxys.speed \n LIMIT %(param_1)s'] [parameters: [{}]]

**Comment by lawmillion** [comment]
在docker环境下，官方的python2.7
