### ISSUE TITLE
访问http://httpbin.org/ip失败，请检查网络连接

### ISSUE THREAD

**Issue by Zhanweelee** [qiyeboy/IPProxyPool#69]
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "IPProxy/spider/ProxyCrawl.py", line 26, in startProxyCrawl
    crawl.run()
  File "IPProxy/spider/ProxyCrawl.py", line 44, in run
    myip = getMyIP()
  File "IPProxy/validator/Validator.py", line 160, in getMyIP
    raise Test_URL_Fail
Test_URL_Fail: 访问http://httpbin.org/ip失败，请检查网络连接

 经常报这个错，直接去 curl http://httpbin.org/ip 又有正常的返回。

**Comment by ginsonwang** [comment]
httpbin.org/ip 这个网站有时会无法访问
建议修改一下validator.py文件中的getMyIP函数，换一个更稳定的测试地址

**Comment by Zhanweelee** [comment]
我这边调整了 TEST_IP 和 getMyIP 函数了临时避免了这个问题。

**Comment by qiyeboy** [comment]
好的，谢谢

**Comment by gaoda1234** [comment]
建议用下面这个

**Comment by gaoda1234** [comment]
http://1212.ip138.com/ic.asp
