### ISSUE TITLE
clone下来 修改了一些问题后，运行报错 RuntimeError: cannot release un-acquired lock

### ISSUE THREAD

**Issue by LZleejean** [qiyeboy/IPProxyPool#76]
我的是python35，初步查了下这个问题，好像是queue和threading模块自己的bug，目前不知道怎么解决。
运行结果如下：
Traceback (most recent call last):
  File "D:/Program Files/Python35Work/IPProxyPool/IPProxy.py", line 7, in <module>
    from validator.Validator import validator, getMyIP
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 171, in __exit__
  File "<frozen importlib._bootstrap>", line 123, in release
RuntimeError: cannot release un-acquired lock

**Comment by zpz351348924** [comment]
我的是python3.6,修复了一些包调用错误后也跟你一样了。这个应该是异步多进程锁没有释放，不太会
