### ISSUE TITLE
Test_URL_Fail：主程序运行一段时间后，验证代理可用性时经常报网络连接错误

### ISSUE THREAD

**Issue by Zhiwei1996** [qiyeboy/IPProxyPool#79]
如题，我在config.py配置文件里把验证代理的时长从30分钟缩短到一分钟后，运行检测代理进程会报错
`Process Process-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wangzhiwei/myGitHub/IPProxyPool/spider/ProxyCrawl.py", line 26, in startProxyCrawl
    crawl.run()
  File "/Users/wangzhiwei/myGitHub/IPProxyPool/spider/ProxyCrawl.py", line 44, in run
    myip = getMyIP()
  File "/Users/wangzhiwei/myGitHub/IPProxyPool/validator/Validator.py", line 160, in getMyIP
    raise Test_URL_Fail
Test_URL_Fail: 访问http://httpbin.org/ip失败，请检查网络连接`
错误信息如上，这时进程会卡住一段时间，之后会重启

**Comment by qiyeboy** [comment]
已经更新了，但是希望不要把验证时间变这么短，很多人都在用这个，校验太频繁会容易被封ip
