### ISSUE TITLE
ModuleNotFoundError: No module named 'sqlalchemy'

### ISSUE THREAD

**Issue by sangli00** [qiyeboy/IPProxyPool#87]
[root@bogon IPProxyPool-master]# python  IPProxy.py
Traceback (most recent call last):
  File "/home/IPProxyPool-master/db/DataStore.py", line 13, in <module>
    from db.SqlHelper import SqlHelper as SqlHelper
  File "/home/IPProxyPool-master/db/SqlHelper.py", line 3, in <module>
    from sqlalchemy import Column, Integer, String, DateTime, Numeric, create_engine, VARCHAR
ModuleNotFoundError: No module named 'sqlalchemy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "IPProxy.py", line 4, in <module>
    from api.apiServer import start_api_server
  File "/home/IPProxyPool-master/api/apiServer.py", line 9, in <module>
    from db.DataStore import sqlhelper
  File "/home/IPProxyPool-master/db/DataStore.py", line 17, in <module>
    raise Con_DB_Fail
util.exception.Con_DB_Fail: <exception str() failed>
[root@bogon IPProxyPool-master]# pip3 install sqlalchemy
Requirement already satisfied: sqlalchemy in /usr/lib/python3.4/site-packages
[root@bogon IPProxyPool-master]#

操作系统为centos7

**Comment by err0r10** [comment]
Module sqlalchemy installed?
#Example: pip install SQLAlchemy

**Comment by sangli00** [comment]
I know what happen in this error.
My OS python is error. I change python version is OK.Thanks.
@err0r10
