### ISSUE TITLE
I have downloaded the latest code on 2017-04-19,but displayed the following wrong message.I am begging your help

### ISSUE THREAD

**Issue by hklliang** [qiyeboy/IPProxyPool#88]
Traceback (most recent call last):
  File "F:/pkfare/ctrip/IPProxyPool-master/IPProxy.py", line 7, in <module>
    from validator.Validator import validator, getMyIP
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 154, in __exit__
  File "<frozen importlib._bootstrap>", line 106, in release
RuntimeError: cannot release un-acquired lock

**Comment by hklliang** [comment]
mysql is no problem except mongodb

**Comment by qiyeboy** [comment]
希望将所用包的版本和python版本发一下，我没有复现出你这种情况

**Comment by hklliang** [comment]
aiomysql (0.0.9)
alabaster (0.7.9)
anaconda-client (1.6.0)
anaconda-navigator (1.4.3)
astroid (1.4.9)
astropy (1.3)
attrs (16.3.0)
Automat (0.5.0)
Babel (2.3.4)
backports.shutil-get-terminal-size (1.0.0)
beautifulsoup4 (4.5.3)
bitarray (0.8.1)
blaze (0.10.1)
bokeh (0.12.4)
boto (2.45.0)
Bottleneck (1.2.0)
cffi (1.9.1)
chardet (2.3.0)
chest (0.2.3)
click (6.7)
cloudpickle (0.2.2)
clyent (1.2.2)
colorama (0.3.7)
comtypes (1.1.2)
conda (4.3.16)
configobj (5.0.6)
constantly (15.1.0)
contextlib2 (0.5.4)
cryptography (1.7.1)
cssselect (1.0.1)
cycler (0.10.0)
Cython (0.25.2)
cytoolz (0.8.2)
dask (0.13.0)
datashape (0.5.4)
decorator (4.0.11)
dill (0.2.5)
docutils (0.13.1)
et-xmlfile (1.0.1)
fake-useragent (0.1.7)
fastcache (1.0.2)
Flask (0.12)
Flask-Cors (3.0.2)
fuzzywuzzy (0.15.0)
gevent (1.2.0)
greenlet (0.4.11)
h5py (2.6.0)
HeapDict (1.0.0)
idna (2.2)
imagesize (0.7.1)
incremental (16.10.1)
ipykernel (4.5.2)
ipython (5.1.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
isort (4.2.5)
itsdangerous (0.24)
jdcal (1.3)
jedi (0.9.0)
Jinja2 (2.9.4)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-core (4.2.1)
lazy-object-proxy (1.2.2)
llvmlite (0.15.0)
locket (0.2.0)
lxml (3.7.1)
MarkupSafe (0.23)
matplotlib (2.0.0)
menuinst (1.4.4)
mistune (0.7.3)
mpmath (0.19)
multipledispatch (0.4.9)
mysqlclient (1.3.10)
nbconvert (4.2.0)
nbformat (4.2.0)
networkx (1.11)
nltk (3.2.2)
nose (1.3.7)
notebook (4.3.1)
numba (0.30.1)
numexpr (2.6.1)
numpy (1.11.3)
numpydoc (0.6.0)
odo (0.5.0)
openpyxl (2.4.1)
pandas (0.19.2)
parsel (1.1.0)
partd (0.3.7)
path.py (0.0.0)
pathlib2 (2.2.0)
patsy (0.4.1)
pbr (2.1.0)
pep8 (1.7.0)
pickleshare (0.7.4)
Pillow (4.0.0)
pip (9.0.1)
ply (3.9)
prompt-toolkit (1.0.9)
psutil (5.0.1)
py (1.4.32)
pyasn1 (0.1.9)
pyasn1-modules (0.0.8)
pycosat (0.6.1)
pycparser (2.17)
pycrypto (2.6.1)
pycurl (7.43.0)
PyDispatcher (2.0.5)
pyflakes (1.5.0)
Pygments (2.1.3)
pylint (1.6.4)
pymongo (3.4.0)
PyMySQL (0.7.11)
pyOpenSSL (16.2.0)
pyparsing (2.1.4)
pytest (3.0.5)
python-dateutil (2.6.0)
python-Levenshtein (0.12.0)
pytz (2016.10)
pywin32 (220.1)
PyYAML (3.12)
pyzmq (16.0.2)
QtAwesome (0.4.3)
qtconsole (4.2.1)
QtPy (1.2.1)
queuelib (1.4.2)
redis (2.10.5)
requests (2.12.4)
rope-py3k (0.9.4.post1)
scikit-image (0.12.3)
scikit-learn (0.18.1)
scipy (0.18.1)
Scrapy (1.3.2)
scrapy-redis (0.6.8)
seaborn (0.7.1)
selenium (3.3.3)
service-identity (16.0.0)
setuptools (27.2.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
sockjs-tornado (1.0.3)
sphinx (1.5.1)
splinter (0.7.5)
spyder (3.1.2)
SQLAlchemy (1.1.4)
statsmodels (0.6.1)
stevedore (1.21.0)
sympy (1.0)
tables (3.2.2)
toolz (0.8.2)
tornado (4.4.2)
traitlets (4.3.1)
Twisted (17.1.0)
unicodecsv (0.14.1)
virtualenv (15.1.0)
virtualenv-clone (0.2.6)
virtualenvwrapper (4.7.2)
virtualenvwrapper-win (1.2.1)
w3lib (1.17.0)
wcwidth (0.1.7)
web.py (0.40.dev0)
Werkzeug (0.11.15)
wheel (0.29.0)
widgetsnbextension (1.2.6)
win-unicode-console (0.5)
wrapt (1.10.8)
xlrd (1.0.0)
XlsxWriter (0.9.6)
xlwings (0.10.2)
xlwt (1.2.0)
zope.interface (4.3.3)
python 3.60 64bit
我用你以前的版本是没有问题的

我新开了一个virtualen也是不行
![image](https://cloud.githubusercontent.com/assets/24997125/25220502/9d8c911a-25e4-11e7-83f9-a33a360ac064.png)

**Comment by qiyeboy** [comment]
你先用着之前的v1.0版本，这个我尽快解决

**Comment by qiyeboy** [comment]
这两个gevent (1.2.0)
greenlet (0.4.11)
你升级一下试试

**Comment by hklliang** [comment]
还是一样的报错。。。我在不同的电脑也是一样，另外的电脑是python3.5的

**Comment by yajiedesign** [comment]
同样的问题 Anaconda3 .py3.6
