### ISSUE TITLE
mysql+pymysql程序运行出错系统windows7*64

### ISSUE THREAD

**Issue by a546284907** [qiyeboy/IPProxyPool#91]
`DB_CONFIG = {
                          'DB_CONNECT_TYPE' : 'sqlalchemy'
                          'DB_CONNECT_STRING' : 'mysql+pymysql://root:root@localhost/proxy?charset=utf8'
}`

C:\Users\Administrator\Desktop\ipproxypool\IPProxyPool-master>python IPProxy.py
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 1122
, in _do_get
    return self._pool.get(wait, self._timeout)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\util\queue.py", lin
e 145, in get
    raise Empty
sqlalchemy.util.queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\engine\base.py", li
ne 2147, in _wrap_pool_connect
    return fn()
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 387,
 in connect
    return _ConnectionFairy._checkout(self)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 766,
 in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 516,
 in checkout
    rec = pool._do_get()
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 1138
, in _do_get
    self._dec_overflow()
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\util\langhelpers.py
", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\util\compat.py", li
ne 187, in reraise
    raise value
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 1135
, in _do_get
    return self._create_connection()
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 333,
 in _create_connection
    return _ConnectionRecord(self)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 461,
 in __init__
    self.__connect(first_connect_check=True)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 651,
 in __connect
    connection = pool._invoke_creator(self)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\engine\strategies.p
y", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\engine\default.py",
 line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "D:\Program Files\python\lib\site-packages\pymysql\__init__.py", line 90,
 in Connect
    return Connection(*args, **kwargs)
  File "D:\Program Files\python\lib\site-packages\pymysql\connections.py", line
706, in __init__
    self.connect()
  File "D:\Program Files\python\lib\site-packages\pymysql\connections.py", line
932, in connect
    self._request_authentication()
  File "D:\Program Files\python\lib\site-packages\pymysql\connections.py", line
1152, in _request_authentication
    auth_packet = self._read_packet()
  File "D:\Program Files\python\lib\site-packages\pymysql\connections.py", line
1014, in _read_packet
    packet.check_error()
  File "D:\Program Files\python\lib\site-packages\pymysql\connections.py", line
393, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\python\lib\site-packages\pymysql\err.py", line 107, in
raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1049, "Unknown database 'proxy'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ipproxypool\IPProxyPool-master\db\DataSto
re.py", line 15, in <module>
    sqlhelper.init_db()
  File "C:\Users\Administrator\Desktop\ipproxypool\IPProxyPool-master\db\SqlHelp
er.py", line 47, in init_db
    BaseModel.metadata.create_all(self.engine)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\sql\schema.py", lin
e 3885, in create_all
    tables=tables)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\engine\base.py", li
ne 1928, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "D:\Program Files\python\lib\contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\engine\base.py", li
ne 1921, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\engine\base.py", li
ne 2112, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\engine\base.py", li
ne 2151, in _wrap_pool_connect
    e, dialect, self)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\engine\base.py", li
ne 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\util\compat.py", li
ne 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\util\compat.py", li
ne 186, in reraise
    raise value.with_traceback(tb)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\engine\base.py", li
ne 2147, in _wrap_pool_connect
    return fn()
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 387,
 in connect
    return _ConnectionFairy._checkout(self)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 766,
 in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 516,
 in checkout
    rec = pool._do_get()
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 1138
, in _do_get
    self._dec_overflow()
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\util\langhelpers.py
", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\util\compat.py", li
ne 187, in reraise
    raise value
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 1135
, in _do_get
    return self._create_connection()
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 333,
 in _create_connection
    return _ConnectionRecord(self)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 461,
 in __init__
    self.__connect(first_connect_check=True)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\pool.py", line 651,
 in __connect
    connection = pool._invoke_creator(self)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\engine\strategies.p
y", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "D:\Program Files\python\lib\site-packages\sqlalchemy\engine\default.py",
 line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "D:\Program Files\python\lib\site-packages\pymysql\__init__.py", line 90,
 in Connect
    return Connection(*args, **kwargs)
  File "D:\Program Files\python\lib\site-packages\pymysql\connections.py", line
706, in __init__
    self.connect()
  File "D:\Program Files\python\lib\site-packages\pymysql\connections.py", line
932, in connect
    self._request_authentication()
  File "D:\Program Files\python\lib\site-packages\pymysql\connections.py", line
1152, in _request_authentication
    auth_packet = self._read_packet()
  File "D:\Program Files\python\lib\site-packages\pymysql\connections.py", line
1014, in _read_packet
    packet.check_error()
  File "D:\Program Files\python\lib\site-packages\pymysql\connections.py", line
393, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\python\lib\site-packages\pymysql\err.py", line 107, in
raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1049, "Unknown databa
se 'proxy'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "IPProxy.py", line 5, in <module>
    from api.apiServer import start_api_server
  File "C:\Users\Administrator\Desktop\ipproxypool\IPProxyPool-master\api\apiSer
ver.py", line 9, in <module>
    from db.DataStore import sqlhelper
  File "C:\Users\Administrator\Desktop\ipproxypool\IPProxyPool-master\db\DataSto
re.py", line 17, in <module>
    raise Con_DB_Fail
util.exception.Con_DB_Fail: <exception str() failed>

C:\Users\Administrator\Desktop\ipproxypool\IPProxyPool-master>

**Comment by qiyeboy** [comment]
你可能在mysql中没有新建proxy数据库

**Comment by a546284907** [comment]
@qiyeboy 确实没有建立数据库，要添加表么？

**Comment by a546284907** [comment]
@qiyeboy 问题已经解决，谢谢大神
